import { MetadataRoute } from "next";
import { getCanonicalUrl } from "@/lib/config/site";

export const revalidate = 86400;

export default function robots(): MetadataRoute.Robots {
  const sitemapUrl = getCanonicalUrl("/sitemap.xml");

  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/movies",
          "/series",
          "/anime",
          "/anime/",
          "/trending",
          "/top-rated",
          "/upcoming",
          "/new",
          "/trailers",
          "/categories",
          "/category/",
          "/genre/",
          "/movie/",
          "/movies/",
          "/tv/",
          "/series/",
          "/person/",
          "/collection/",
          "/country/",
          "/language/",
          "/kdrama",
          "/cdrama",
          "/kids",
          "/documentaries",
          "/terms",
          "/privacy",
          "/sitemap.xml",
          "/robots.txt",
        ],
        disallow: [
          "/api/",
          "/admin",
          "/admin/",
          "/account",
          "/account/",
          "/private",
          "/private/",
          "/internal",
          "/internal/",
          "/login",
          "/register",
          "/forgot-password",
          "/reset-password",
          "/change-password",
          "/profile",
          "/profile/",
          "/watchlist",
          "/watchlist/",
          "/my-list",
          "/my-list/",
          "/history",
          "/history/",
          "/watch/",
          "/embed/",
          "/search",
          "/intro",
        ],
      },
      {
        userAgent: "Googlebot",
        allow: [
          "/",
          "/movies",
          "/series",
          "/anime",
          "/anime/",
          "/trending",
          "/top-rated",
          "/upcoming",
          "/new",
          "/trailers",
          "/categories",
          "/category/",
          "/genre/",
          "/movie/",
          "/movies/",
          "/tv/",
          "/series/",
          "/person/",
          "/collection/",
          "/country/",
          "/language/",
          "/kdrama",
          "/cdrama",
          "/kids",
          "/documentaries",
          "/terms",
          "/privacy",
          "/sitemap.xml",
          "/robots.txt",
        ],
        disallow: [
          "/api/",
          "/admin",
          "/admin/",
          "/account",
          "/account/",
          "/private",
          "/private/",
          "/internal",
          "/internal/",
          "/login",
          "/register",
          "/forgot-password",
          "/reset-password",
          "/change-password",
          "/profile",
          "/profile/",
          "/watchlist",
          "/watchlist/",
          "/my-list",
          "/my-list/",
          "/history",
          "/history/",
          "/watch/",
          "/embed/",
          "/search",
          "/intro",
        ],
      },
    ],
    sitemap: sitemapUrl,
  };
}
